### ISSUE TITLE
Chunking input list

### ISSUE THREAD

**Issue by iancze** [kevinkhu/Starfish#1]
We need a list of wavelength bounds to create "chunks" of spectra.

Ideally, these would be well-motivated wavelengths of ~50A each, which hopefully correspond to distinct molecular regions or parameter-sensitive regions.

These chunks would be identical to all stars that we are analyzing, so that we may later link correlations between chunks.

**Comment by kevinkhu** [comment]
Here is the first pass at the wavelength chunks, taking into account almost all molecular bands pertinent to M dwarfs.
[chunks.txt](https://github.com/kevinkhu/Starfish/files/637824/chunks.txt)

**Comment by kevinkhu** [comment]
A visual representation of the wavelength chunks
[GJ581.pdf](https://github.com/kevinkhu/Starfish/files/637938/GJ581.pdf)

**Comment by iancze** [comment]
Looks great!
